# Generated by Django 4.1.4 on 2023-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=500, verbose_name='İçerik')),
                ('date_now', models.DateTimeField(verbose_name='Tarih Saat')),
            ],
        ),
    ]
