# Generated by Django 4.1.4 on 2023-01-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(max_length=500, verbose_name='İçerik')),
                ('date_now', models.DateTimeField(verbose_name='Tarih Saat')),
                ('price', models.IntegerField(null=True, verbose_name='Fiyat')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Ürün Resmi')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
            ],
        ),
    ]
