# Generated by Django 4.1.4 on 2023-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Fiyat'),
        ),
    ]
