# Generated by Django 4.1.4 on 2023-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yorum Yapılma Zamanı'),
        ),
    ]
