# Generated by Django 4.1.4 on 2023-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_card_brand_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Ürün Resmi'),
        ),
    ]
