# Generated by Django 4.1.4 on 2023-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Ürün Resmi'),
        ),
    ]
